name: "Deployment Lifecycle: Create Deployment from Label"
description: "Create a deployment from a 'deploy to' label"
author: "Colin Dembovsky"
inputs:
  environment-regex:
    description: The regex to extract the deployment name from the label
    required: false
    default: 'deploy to (\w+)'
  create-comment:
    description: Set to true to create a comment on the PR
    required: false
    default: "true"
  deployment-workflow-name:
    description: Name of the workflow to invoke to run the deployment logic e.g. deployApp.yml
    required: true
  additional-inputs-json:
    description: >-
      JSON string of additional inputs to pass to the workflow. 
      These are merged with { environment: <env_name> } and passed to the deployment workflow.
      This requires the deployment workflow to accept at least the "environment" input parameter e.g.
      on:
        workflow_dispatch:
          inputs:
            environment:
              description: The name of the environment to be deployed
              required: true
  token:
    description: Token with permissions to perform REST API calls to the repository
    default: ${{ github.token }}
outputs:
  environment:
    description: Name of the environment
runs:
  using: "node16"
  main: "../lib/create-deployment-from-label.js"